CREATE TABLE Campaign (
  CampaignID bigserial primary key,
  CampaignHash varchar(32) NOT NULL,
  AdvertiserID int DEFAULT NULL,
  CampaignName varchar(200) DEFAULT NULL,
  URL text NOT NULL,
  ExampleURL text NOT NULL,
  RedirectType varchar(50) NOT NULL DEFAULT 'frame',
  InsertDate timestamp NOT NULL,
  IsActive smallint NOT NULL DEFAULT 1,
  IsDeleted smallint NOT NULL DEFAULT 0,
  CategoryID int NOT NULL DEFAULT 0,
  AppID varchar(100) DEFAULT NULL,
  IncentAllowed smallint NOT NULL DEFAULT 0,
  Country text NOT NULL,
  Currency varchar(3) NOT NULL,
  CPA int NOT NULL DEFAULT 0,
  PartnerCurrency varchar(3) DEFAULT NULL,
  PartnerCPA int NOT NULL DEFAULT 0,
  AllowPartnerApplication smallint NOT NULL DEFAULT 0,
  OfferTitle text DEFAULT NULL,
  OfferText text DEFAULT NULL,
  Notes text DEFAULT NULL,
  AllowedOnPath smallint NOT NULL DEFAULT 0,
  PublisherNotes text NOT NULL,
  AdminLoginID int NOT NULL DEFAULT 2,
  ConversionPoint varchar(12) NOT NULL DEFAULT 'lead',
  UseGeoTargeting smallint NOT NULL DEFAULT 1,
  ShowOnSites varchar(20) NOT NULL DEFAULT '1',
  DailyCap int NOT NULL DEFAULT 0,
  TotalCap int NOT NULL DEFAULT 0,
  TotalCapResetDate timestamp DEFAULT NULL,
  TotalCapResetAdjustment int DEFAULT NULL,
  Platforms varchar(200) DEFAULT NULL,
  MinOSVersion varchar(50) DEFAULT NULL,
  IsDeviceMandatory smallint NOT NULL DEFAULT 0,
  DeviceIDList varchar(200) DEFAULT NULL,
  PayoutType varchar(10) DEFAULT NULL,
  CampaignStartDate timestamp DEFAULT NULL,
  CampaignEndDate timestamp DEFAULT NULL,
  TrafficType varchar(50) DEFAULT '1',
  AdvertiserRef varchar(200) DEFAULT NULL,
  Country2 text DEFAULT NULL,
  TrafficQualityID smallint NOT NULL DEFAULT 0,
  TrafficQualityInclusion varchar(1500) DEFAULT NULL,
  TrafficQualityExclusion varchar(1500) DEFAULT NULL,
  AdvertiserCampaignID int DEFAULT NULL
);

